[tools]
azure-cli = "latest"
java = "21"

[tasks."setup:amper"]
description = "Amper CLIをダウンロードしてセットアップ"
run = """
curl -fsSL -o amper https://jb.gg/amper/wrapper.sh
chmod +x amper
./amper update -c
"""

[tasks.build]
description = "Build client/server modeules"
run = """
cd client && ../amper build && cd ..
mkdir -p server/public/build/tasks/_client_linkJs/
cp client/index.html server/public/
cp client/build/tasks/_client_linkJs/client.mjs server/public/build/tasks/_client_linkJs/
"""
