[tools]
azure-cli = "latest"
java = "21"

[tasks."setup:amper"]
description = "Amper CLIをダウンロードしてセットアップ"
run = """
curl -fsSL -o amper https://jb.gg/amper/wrapper.sh
chmod +x amper
./amper update -c
"""

[tasks.serve]
description = "Webクライアントをホスト"
run = "python3 -m http.server 8081 --directory client"
