[tools]
python = "3.10.11"
pipx = "latest"
azure-cli = "latest"
java = "21"

[tasks."setup:amper"]
description = "Amper CLIをダウンロードしてセットアップ"
run = """
curl -fsSL -o amper https://jb.gg/amper/wrapper.sh
chmod +x amper
./amper update -c
"""

[tasks."setup:python"]
description = "Python仮想環境のセットアップ"
run = "python -m venv .venv && .venv/bin/pip install --upgrade pip"

[tasks.build]
description = "Build client/server modeules"
depends = ["setup:amper"]
run = """
cd client && ../amper build && cd ..
mkdir -p server/public/build/tasks/_client_linkJs/
cp client/index.html server/public/
cp client/build/tasks/_client_linkJs/client.mjs server/public/build/tasks/_client_linkJs/
"""

[tasks.deploy]
description = "Deploy to Azure"
depends = ["build"]
run = """
bash ./deploy.sh
"""
