services:
  # NAT1 Network Client
  client-nat1:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8181:6080"
    environment:
      - TARGET_URL=http://host.docker.internal:49880/index.html
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "turn:host-gateway"
    networks:
      - nat1

  client-nat1-2:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8185:6080"
    environment:
      - TARGET_URL=http://host.docker.internal:49880/index.html
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "turn:host-gateway"
    networks:
      - nat1

  # NAT2 Network Client
  client-nat2:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8182:6080"
    environment:
      - TARGET_URL=http://host.docker.internal:49880/index.html
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "turn:host-gateway"
    networks:
      - nat2

  # PXY1 Network Client & Proxy
  client-pxy1:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8183:6080"
    environment:
      - TARGET_URL=http://host.docker.internal:49880/index.html
      - HTTP_PROXY=http://proxy1:3128
      - HTTPS_PROXY=http://proxy1:3128
      - NO_PROXY=localhost,127.0.0.1,host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "turn:host-gateway"
    networks:
      - pxy1
    depends_on:
      - proxy1

  client-pxy1-2:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8186:6080"
    environment:
      - TARGET_URL=http://host.docker.internal:49880/index.html
      - HTTP_PROXY=http://proxy1:3128
      - HTTPS_PROXY=http://proxy1:3128
      - NO_PROXY=localhost,127.0.0.1,host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "turn:host-gateway"
    networks:
      - pxy1
    depends_on:
      - proxy1

  proxy1:
    image: ubuntu/squid:latest
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pxy1
      - webrtc-shared-net

  # PXY2 Network Client & Proxy
  client-pxy2:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8184:6080"
    environment:
      - TARGET_URL=http://host.docker.internal:49880/index.html
      - HTTP_PROXY=http://proxy2:3128
      - HTTPS_PROXY=http://proxy2:3128
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "turn:host-gateway"
    networks:
      - pxy2
    depends_on:
      - proxy2

  proxy2:
    image: ubuntu/squid:latest
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pxy2
      - webrtc-shared-net

networks:
  nat1:
    driver: bridge
  nat2:
    driver: bridge
  pxy1:
    driver: bridge
  pxy2:
    driver: bridge
  webrtc-shared-net:
    name: webrtc-shared-net-14
    external: true
